%YAML:1.0
cameras:
    # Stereo Left (cam 0)
  - {T_SC: [-0.07114084, -0.39925794,  0.91407444,  0.0038567,
            0.99700878, -0.00071059,  0.0772851,  -0.0005779,
            -0.03020716,  0.91683837,  0.39811422,  0.00217015,
            0.0  , 0.0, 0.0  , 1.0] ,
     image_dimension: [640, 360],
     distortion_type: equidistant,
     distortion_coefficients: [-0.036659423566449606, 0.01873386072335892, -0.03762330184773268, 0.02041945926074395],
     focal_length: [363.5578420995749, 363.44352078091345],
     principal_point: [320.1219054868866, 184.28450088887164],
     cam_model: pinhole,
     camera_type: gray+depth,
     mapping: true,
     mapping_rectification: true,
     slam_use: okvis}
     
     # Stereo Right (cam 1)
  - {T_SC: [ 0.06433189, -0.40560566,  0.91178148,  0.00375051,
             0.99746027, -0.00185226, -0.07120104,  0.19323301,
             0.0305684,   0.91404629,  0.40445637,  0.00113733,
            0.0  , 0.0, 0.0  , 1.0] ,
     image_dimension: [640, 360],
     distortion_coefficients: [-0.03272986676871673, -0.003245176122440311, 0.011794589260422083, -0.01133065639188429],
     distortion_type: equidistant,
     focal_length: [363.16280486995685, 363.00730154124825],
     principal_point: [334.1653314650457, 184.84724275293215],
     cam_model: pinhole,
     camera_type: gray, #gray, rgb, gray+depth, rgb+depth 
     mapping: true,
     mapping_rectification: true,
     slam_use: okvis} #none, okvis, okvis-depth, okvis-virtual
          
camera_parameters:
    timestamp_tolerance: 0.005 # [s] stereo frame out-of-sync tolerance
    sync_cameras: [0, 1] # the cameras that will be synchronised
    image_delay: 0.0 # [s] timestamp_camera_correct = timestamp_camera - image_delay
    online_calibration: # some parameters to set the online
        do_extrinsics: false  # Simulator has known extrinsics
        do_extrinsics_final_ba: false
        sigma_r: 0.01 # T_SCi position prior stdev [m]
        sigma_alpha: 0.1 # T_SCi orientation prior stdev [rad]
        sigma_r_final_ba: 0.03 # T_SCi position prior stdev in final BA [m]
        sigma_alpha_final_ba: 0.3 # T_SCi orientation prior stdev in final BA [rad]
    deep_stereo_indices: [0,1] # [left, right] camera indices for the stereo network
    fov_scale: 1.0 # Divisor for new focal length which is only used when fisheye stereo rectification for dense mapping.

imu_parameters:
    use: true
    a_max: 176.0 # acceleration saturation [m/s^2] (PX4 default)
    g_max: 7.8 # gyro saturation [rad/s] (PX4 default)
    sigma_g_c: 6.447192398374904e-02
    sigma_a_c: 0.1041716817202322     # accelerometer noise density [m/s^2/sqrt(Hz)]
    sigma_bg: 4.027e-02  # gyro bias prior [rad/s]
    sigma_ba: 4.827e-01 # accelerometer bias prior [m/s^2]
    sigma_gw_c: 5.4968240967256775e-04 # gyro drift noise density [rad/s^s/sqrt(Hz)]
    sigma_aw_c: 3.5309908618458486e-2 # accelerometer drift noise density [m/s^2/sqrt(Hz)]
    g: 9.81007 # Earth's acceleration due to gravity [m/s^2]
    g0: [0.0, 0.0, 0.0] # initial gyroscope bias [rad/s]
    a0: [0.0, 0.0, 0.0] # initial accelerometer bias [m/s^2]
    s_a: [1.0,1.0,1.0]

    T_BS:
        [1.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 1.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 1.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 1.0000]

# frontend: detection etc.
frontend_parameters:
    detection_threshold: 38.0 # detection threshold. By default the uniformity radius in pixels
    absolute_threshold: 250.0 # absolute Harris corner threshold (noise floor)
    matching_threshold: 60.0 # BRISK descriptor matching threshold
    octaves: 0 # number of octaves for detection. 0 means single-scale at highest resolution
    max_num_keypoints: 400 # restrict to a maximum of this many keypoints per image (strongest ones)
    keyframe_overlap: 0.60 # minimum field-of-view overlap
    use_cnn: false # use the CNN (if available) to filter out dynamic content / sky
    parallelise_detection: true # Run parallel detect & describe.
    num_matching_threads: 4 # Parallelise matching with this number of threads.

# estimator parameters
estimator_parameters:
    num_keyframes: 5 # number of keyframes in optimisation window
    num_loop_closure_frames: 3 # number of loop closure frames in optimisation window
    num_imu_frames: 3 # number of frames linked by most recent nonlinear IMU error terms
    do_loop_closures: true # whether to do VI-SLAM or VIO
    do_final_ba: true # Whether to run a full final BA
    enforce_realtime: false # whether to limit the time budget for optimisation
    realtime_min_iterations: 3 # minimum number of iterations always performed
    realtime_max_iterations: 10 # never do more than these, even if not converged
    realtime_time_limit: 0.035 # time budget for realtime optimisation [s]
    realtime_num_threads: 3 # number of threads for the realtime optimisation
    full_graph_iterations: 15 # don't do more than these for the full (background) optimisation
    full_graph_num_threads: 3 # number of threads for the full (background) optimisation
    p_dbow: 0.35 # Match threshold for dBoW -- unfortunately this varies with setups.
    drift_percentage_heuristic: 1.35 # 2.5 # % allowed drift in loop closures rel. to dist. travelled.

# some options for how and what to output
output_parameters:
    display_topview: true # Displays top view of the trajectory. Might become slow for long sequences.
    display_matches: true  # displays debug video and matches. May be slow.
    display_overhead: false # debug overhead image. Is slow.
    enable_submapping: true # Enable volumetric submapping
