%YAML:1.0
cameras:
    # Stereo Left (cam 0)
  - {T_SC: [-0.01462683, -0.38037337,  0.92471734,  0.0884588,
        0.99982454, -0.01638738,  0.00907406, -0.13647743,
        0.01170216,  0.92468781,  0.38054633,  0.14169152,
        0.,          0.,          0.,          1.        ],
     image_dimension: [640, 360],
     distortion_type: equidistant,
     distortion_coefficients: [-0.2206115868429776, 0.8231590422789293, -1.9681164167591725, 1.6469311676844083],
     focal_length:  [407.351378073769, 406.97812172493],
     principal_point:  [315.77438652919636, 177.12693199336775],
     cam_model: pinhole,
     camera_type: gray+depth,
     mapping: true,
     mapping_rectification: true,
     slam_use: okvis}
     
     # Stereo Right (cam 1)
  - {T_SC: [-0.02836091, -0.3819827,   0.9237342,   0.08221052,
        0.99955877, -0.01899814,  0.02283279,  0.06404161,
        0.0088275,   0.92397418,  0.38235296,  0.14209826,
        0.,          0.,          0.,          1.        ],
     image_dimension: [640, 360],
     distortion_coefficients: [-0.6528255535522096, 4.9294995979568785, -15.917904369020045, 16.953934484580905],
     distortion_type: equidistant,
     focal_length: [413.1960175983617, 413.1991495539231],
     principal_point: [302.0780322224247, 185.62581447146772],
     cam_model: pinhole,
     camera_type: gray, #gray, rgb, gray+depth, rgb+depth 
     mapping: true,
     mapping_rectification: true,
     slam_use: okvis} #none, okvis, okvis-depth, okvis-virtual
          
camera_parameters:
    timestamp_tolerance: 0.005 # [s] stereo frame out-of-sync tolerance
    sync_cameras: [0, 1] # the cameras that will be synchronised
    image_delay: 0.0 # [s] timestamp_camera_correct = timestamp_camera - image_delay
    online_calibration: # some parameters to set the online
        do_extrinsics: true  # Simulator has known extrinsics
        do_extrinsics_final_ba: false
        sigma_r: 0.01 # T_SCi position prior stdev [m]
        sigma_alpha: 0.1 # T_SCi orientation prior stdev [rad]
        sigma_r_final_ba: 0.03 # T_SCi position prior stdev in final BA [m]
        sigma_alpha_final_ba: 0.3 # T_SCi orientation prior stdev in final BA [rad]
    deep_stereo_indices: [0,1] # [left, right] camera indices for the stereo network
    fov_scale: 1.0 # Divisor for new focal length which is only used when fisheye stereo rectification for dense mapping.

imu_parameters:
    use: true
    a_max: 163.84 # acceleration saturation [m/s^2] (PX4 default)
    g_max: 5.72 # gyro saturation [rad/s] (PX4 default)
    sigma_g_c: 6.790355692422306e-04      # gyro noise density [rad/s/sqrt(Hz)] <- imu_challenger.yaml gyroscope_noise_density
    sigma_a_c: 0.010894695987700165      # accelerometer noise density [m/s^2/sqrt(Hz)] <- imu_challenger.yaml accelerometer_noise_density
    sigma_bg: 4.027038e-03  # gyro bias prior [rad/s]
    sigma_ba: 4.827057e-02 # accelerometer bias prior [m/s^2]
    sigma_gw_c: 1.8484762878126347e-05    # gyro drift noise density [rad/s^2/sqrt(Hz)] <- imu_challenger.yaml gyroscope_random_walk
    sigma_aw_c: 5.2811480875574934e-04    # accelerometer drift noise density [m/s^2/sqrt(Hz)] <- imu_challenger.yaml accelerometer_random_walk
    g: 9.8100776 # Earth's acceleration due to gravity [m/s^2]
    g0: [0.0, 0.0, 0.0] # initial gyroscope bias [rad/s]
    a0: [0.0, 0.0, 0.0] # initial accelerometer bias [m/s^2]
    s_a: [1.0,1.0,1.0]

    T_BS:
        [1.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 1.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 1.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 1.0000]

# frontend: detection etc.
frontend_parameters:
    detection_threshold: 38.0 # detection threshold. By default the uniformity radius in pixels
    absolute_threshold: 200.0 # absolute Harris corner threshold (noise floor)
    matching_threshold: 60.0 # BRISK descriptor matching threshold
    octaves: 0 # number of octaves for detection. 0 means single-scale at highest resolution
    max_num_keypoints: 400 # restrict to a maximum of this many keypoints per image (strongest ones)
    keyframe_overlap: 0.60 # minimum field-of-view overlap
    use_cnn: false # use the CNN (if available) to filter out dynamic content / sky
    parallelise_detection: true # Run parallel detect & describe.
    num_matching_threads: 4 # Parallelise matching with this number of threads.

# estimator parameters
estimator_parameters:
    num_keyframes: 5 # number of keyframes in optimisation window
    num_loop_closure_frames: 3 # number of loop closure frames in optimisation window
    num_imu_frames: 3 # number of frames linked by most recent nonlinear IMU error terms
    do_loop_closures: true # whether to do VI-SLAM or VIO
    do_final_ba: false # Whether to run a full final BA
    enforce_realtime: true # whether to limit the time budget for optimisation
    realtime_min_iterations: 3 # minimum number of iterations always performed
    realtime_max_iterations: 10 # never do more than these, even if not converged
    realtime_time_limit: 0.035 # time budget for realtime optimisation [s]
    realtime_num_threads: 4 # number of threads for the realtime optimisation
    full_graph_iterations: 15 # don't do more than these for the full (background) optimisation
    full_graph_num_threads: 3 # number of threads for the full (background) optimisation
    p_dbow: 0.35 # Match threshold for dBoW -- unfortunately this varies with setups.
    drift_percentage_heuristic:  2.5 # % allowed drift in loop closures rel. to dist. travelled.

# some options for how and what to output
output_parameters:
    display_topview: true # Displays top view of the trajectory. Might become slow for long sequences.
    display_matches: false  # displays debug video and matches. May be slow.
    display_overhead: false # debug overhead image. Is slow.
    enable_submapping: true # Enable volumetric submapping
