%YAML:1.0
cameras:
    - {T_SC:
       [0.00344636, -0.32782163, 0.94473335, 0.09714072,
        0.99985981, -0.01435062, -0.00862712, 0.00922538,
        0.01638566, 0.94463064, 0.32772621, -0.00617084,
        0.0, 0.0, 0.0, 1.0],
       image_dimension: [752, 480],
       distortion_coefficients: [-0.3610000617191652, 0.11099310817872736, 0.006331744786970552, 0.001581974430457278],
       distortion_type: radialtangential,
       cam_model: pinhole,
       focal_length: [476.8909241325342, 540.8035940213773],
       principal_point: [391.61298807991415, 227.2452607988636],
       camera_type: gray + depth,
       mapping: true,
       mapping_rectification: true,
       slam_use: okvis}

    - {T_SC:
       [-0.67855744, -0.3100992, 0.66588158, -0.02064297,
        0.68761153, 0.05068992, 0.7243072, 0.16402102,
        -0.25836057, 0.94935189, 0.17883176, 0.13675472,
        0.0, 0.0, 0.0, 1.0],
       image_dimension: [752, 480],
       distortion_coefficients: [-0.3219116709335815, 0.07658883083754373, 0.008022539267279213, -0.004206167901764695],
       distortion_type: radialtangential,
       cam_model: pinhole,
       focal_length: [455.37837432358435, 514.408043462692],
       principal_point: [387.3673846665898, 216.11712989395488],
       camera_type: gray,
       mapping: true,
       mapping_rectification: true,
       slam_use: okvis}


# additional camera parameters
camera_parameters:
    timestamp_tolerance: 0.005 # [s] stereo frame out-of-sync tolerance
    sync_cameras: [0,1] # the cameras that will be synchronised
    image_delay: 0.00 #64 # [s] timestamp_camera_correct = timestamp_camera - image_delay
    online_calibration: # some parameters to set the online
        do_extrinsics: false # Do we online-calibrate extrinsics?
        do_extrinsics_final_ba: false # Do we calibrate extrinsics in final BA?
        sigma_r: 0.01 # T_SCi position prior stdev [m]
        sigma_alpha: 0.05 # T_SCi orientation prior stdev [rad]
        sigma_r_final_ba: 0.03 # T_SCi position prior stdev in final BA [m]
        sigma_alpha_final_ba: 0.3 # T_SCi orientation prior stdev in final BA [rad]
    deep_stereo_indices: [0,1] # [left, right] camera indices for the stereo network
    fov_scale: 1.0 # Focal length divisor used for dense mapping rectification
    image_masks:
        - camera_index: 0
          regions:
              - [0, 0, 100, 100]      # top-left corner
              - [652, 0, 100, 100]    # top-right corner


imu_parameters:
    use: true
    a_max: 163.84 # acceleration saturation [m/s^2]
    g_max: 5.72 # gyro saturation [rad/s]
    sigma_g_c: 1.294e-02  # gyro noise density [rad/s/sqrt(Hz)]
    sigma_a_c: 2.681358e-01    # accelerometer noise density [m/s^2/sqrt(Hz)]
    sigma_bg: 1.0e00  # gyro bias prior [rad/s]
    sigma_ba: 10.0e00 # accelerometer bias prior [m/s^2]
    sigma_gw_c: 7.618937433225217e-03 # gyro drift noise density [rad/s^s/sqrt(Hz)]
    sigma_aw_c: 6.891330192676646e-03 # accelerometer drift noise density [m/s^2/sqrt(Hz)]
    g: 9.81007 # Earth's acceleration due to gravity [m/s^2]
    g0: [0.0,0.0,0.0]  # initial gyroscope bias [rad/s] for the indoor dataset: --- Bias Estimates ---
    ## Gyro bias (g0) [rad/s]: [-0.00034531  0.0002469   0.0003287 ]
    ## Accel bias (a0) [m/s²]: [-0.00290354 -0.19854035  0.015456  ]
    a0: [-0.00, -0.0, 0.0]  # initial accelerometer bias [m/s^2] for the indoor dataset: --- Bias Estimates ---
    T_BS:
        [1.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 1.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 1.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 1.0000]
    s_a: [1.0, 1.0, 1.0] # accelerometer scale factors

# frontend: detection etc.
frontend_parameters:
    detection_threshold: 38.0 #42.0 # detection threshold. By default the uniformity radius in pixels
    absolute_threshold: 150.0 # absolute Harris corner threshold (noise floor)
    matching_threshold: 60.0 # BRISK descriptor matching threshold
    octaves: 0 # number of octaves for detection. 0 means single-scale at highest resolution
    max_num_keypoints: 700 # restrict to a maximum of this many keypoints per image (strongest ones)
    keyframe_overlap: 0.60 # minimum field-of-view overlap
    use_cnn: false # use the CNN (if available) to filter out dynamic content / sky
    parallelise_detection: true # Run parallel detect & describe.
    num_matching_threads: 4 # Parallelise matching with this number of threads.

# estimator parameters
estimator_parameters:
    num_keyframes: 5 # number of keyframes in optimisation window
    num_loop_closure_frames: 3 # number of loop closure frames in optimisation window
    num_imu_frames: 3 # number of frames linked by most recent nonlinear IMU error terms
    do_loop_closures: true # whether to do VI-SLAM or VIO
    do_final_ba: true # Whether to run a full final BA
    enforce_realtime: false # whether to limit the time budget for optimisation
    realtime_min_iterations: 3 # minimum number of iterations always performed
    realtime_max_iterations: 10 # never do more than these, even if not converged
    realtime_time_limit: 0.035 # time budget for realtime optimisation [s]
    realtime_num_threads: 3 # number of threads for the realtime optimisation
    full_graph_iterations: 15 # don't do more than these for the full (background) optimisation
    full_graph_num_threads: 3 # number of threads for the full (background) optimisation
    p_dbow: 0.4 # Match threshold for dBoW -- unfortunately this varies with setups.
    drift_percentage_heuristic: 1.35 # % allowed drift in loop closures rel. to dist. travelled.

# some options for how and what to output
output_parameters:
    display_topview: true # Displays top view of the trajectory. Might become slow for long sequences.
    display_matches: true  # displays debug video and matches. May be slow.
    display_overhead: false # debug overhead image. Is slow.
    enable_submapping: true # Enable volumetric submapping
